### ISSUE TITLE
Got error while running training script

### ISSUE THREAD

**Issue by tiendung** [Jingjing-NLP/VOLT#3]
```sh
/usr/local/lib/python3.9/site-packages/ot/bregman.py:363: RuntimeWarning: overflow encountered in true_divide
  v = np.divide(b, KtransposeU)
Traceback (most recent call last):
  File "/Users/tamedu/repos/volt/ot_run.py", line 209, in <module>
    optimal_size = run_ot(oldtokens, chars, max_number,interval, num_iter_max) # generate the best ot size
  File "/Users/tamedu/repos/volt/ot_run.py", line 135, in run_ot
    Gs,_ = ot.sinkhorn(a,b,d_matrix,1.0,method='sinkhorn',numItermax=numItermax, epsilon0=1e-6)
ValueError: too many values to unpack (expected 2)
```

**Comment by Jingjing-NLP** [comment]
POT should be installed via local path.  You can try the following commands:
```
cd ../POT
python3 -m pip install --force-reinstall --editable ./ -i https://pypi.doubanio.com/simple --user
```

**Comment by Jingjing-NLP** [comment]
Does this command solve your problem?

**Comment by tiendung** [comment]
I'm following your guide ... Want to add that on my machine I need to `pip3 install cython` before install your local POT.

**Comment by tiendung** [comment]
I got the result. The input vocab is 12k BPE-based and the output is 9k. Does it mean VOLT recommends me using vocabulary size of 9k?

BTW, i wonder what modification you did for POT?

**Comment by kirefu** [comment]
Hi I've been combing through the code, and I think the error lies in the specific sinkhorn method. I think the authors modified some what some of the functions in the POT module returned, specifically one of the sinkhorn methods and we should be using method='sinkhorn_epsilon_scaling' instead. @Jingjing-NLP please could you confirm. Also, rather confusingly, the entropy/matrix variables are switched around between lines 135 and 163

Thanks
https://github.com/Jingjing-NLP/VOLT/blob/c9f2e692b2a25ba6be19d067020d0eeaa288ce55/ot_run.py#L135

https://github.com/Jingjing-NLP/VOLT/blob/c9f2e692b2a25ba6be19d067020d0eeaa288ce55/ot_run.py#L163

**Comment by Jingjing-NLP** [comment]
> Hi @Jingjing-NLP, could you confirm whether the method should be 'sinkhorn' or 'sinkhorn_epsilon_scaling'', given that you are also using epsilon0=1e-6 as an argument. Thanks.

Hi, I use sinkhorn, and epsilon0 is a dead argument... I will delete this argument from the codebase. Thanks for your comments again!
